import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import { useEffect, useState } from 'react';
import {
  Flex,
  Heading,
  Avatar,
  Box,
  Center,
  Text,
  Stack,
  Button,
  Link,
  Badge,
  useColorModeValue,
} from '@chakra-ui/react';
const UserCard = (props) => {
  return (
    <Center py={6}>
      <Box
        maxW={'320px'}
        minH={'320px'}
        w={'full'}
        bg={useColorModeValue('white', 'gray.900')}
        boxShadow={'2xl'}
        rounded={'lg'}
        p={6}
        textAlign={'center'}
        m={['0.5rem', '2rem']}
      >
        <Avatar
          size={'xl'}
          src={props.profilePicture}
          alt={'Avatar Alt'}
          mb={4}
          pos={'relative'}
        />
        <Heading fontSize={'2xl'} fontFamily={'body'}>
          {props.name}
        </Heading>
        <Text fontWeight={400} color={'gray.500'} mb={4} maxW='12rem'>
          {props.email}
        </Text>
        <Text
          textAlign={'center'}
          color={useColorModeValue('gray.700', 'gray.400')}
          px={3}
        >
          Recent test Result
          <Box color={'blue.400'}>
            Score -{' '}
            {props.userScore >= 0 ? props.userScore + '/ 15' : 'No test given'}
          </Box>{' '}
        </Text>
      </Box>
    </Center>
  );
};

export default function Home() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    axios
      .get('https://brightigobackend.herokuapp.com/api/allUsers')
      .then((res) => {
        setUsers(res.data);
        console.log(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, [users]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Center pt={'4rem'} mb='2rem'>
          <Heading>Brightigo Signups 📂</Heading>
        </Center>
        <Flex
          flexDir={'row-reverse'}
          flexWrap={'wrap'}
          alignItems='center'
          justify={'center'}
        >
          {users.length > 0 ? (
            users.map((user) => (
              <UserCard
                key={user.name}
                name={user.name}
                email={user.email}
                profilePicture={user.profilePicture}
                userScore={user.test.score}
              />
            ))
          ) : (
            <Center textColor={'red.300'}>Loading ... </Center>
          )}
        </Flex>
      </>
    </div>
  );
}
